<a href="https://colab.research.google.com/github/madalamanikanta/ImageCaptioning_MiniProject/blob/manikanta-dev/03_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Notebook 03 : Data Preprocessing

# Step 1 : Connect Google Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Step 2 : Import Required Libraries

In [2]:
from pathlib import Path
import pandas as pd
import re
import string

# Step 3 : Define Project Paths

In [3]:
PROJECT_DIR = Path("/content/drive/MyDrive/ImageCaptioning_MiniProject")

PROCESSED_DIR = PROJECT_DIR / "Processed"

merged_file = PROCESSED_DIR / "merged_dataset.csv"

# Step 4 : Load Merged Dataset

In [4]:
df = pd.read_csv(merged_file)

print(df.shape)

df.head()

(599402, 3)

,image_path,caption,dataset
0,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A child in a pink dress is climbing up a set o...,Flickr8K
1,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A girl going into a wooden building .,Flickr8K
2,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A little girl climbing into a wooden playhouse .,Flickr8K
3,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A little girl climbing the stairs to her playh...,Flickr8K
4,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A little girl in a pink dress going into a woo...,Flickr8K

# Step 5 : Dataset Inspection

In [6]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 599402 entries, 0 to 599401
Data columns (total 3 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   image_path  599402 non-null  object
 1   caption     599401 non-null  object
 2   dataset     599402 non-null  object
dtypes: object(3)
memory usage: 13.7+ MB
None

In [7]:
print(df.isnull().sum())

image_path    0
caption       1
dataset       0
dtype: int64

In [8]:
print(df["dataset"].value_counts())

dataset
COCO2017     400077
Flickr30K    158880
Flickr8K      40445
Name: count, dtype: int64

In [12]:
# Create a copy of the dataset
clean_df = df.copy()

print("Original Dataset Size :", len(clean_df))

# Remove rows with missing captions
clean_df = clean_df.dropna(subset=["caption"]).reset_index(drop=True)

print("Dataset Size After Removing Missing Captions :", len(clean_df))

print("\nMissing Captions Remaining :")

print(clean_df["caption"].isnull().sum())

Original Dataset Size : 599402
Dataset Size After Removing Missing Captions : 599401

Missing Captions Remaining :
0

## Step 6 : Create a Backup of the Original Dataset

In [9]:
# Create a copy of the dataset

clean_df = df.copy()
print("Backup created successfully!")
print(clean_df.head())

Backup created successfully!
                                          image_path  \
0  /content/drive/MyDrive/ImageCaptioning_MiniPro...
1  /content/drive/MyDrive/ImageCaptioning_MiniPro...
2  /content/drive/MyDrive/ImageCaptioning_MiniPro...
3  /content/drive/MyDrive/ImageCaptioning_MiniPro...
4  /content/drive/MyDrive/ImageCaptioning_MiniPro...

                                             caption   dataset
0  A child in a pink dress is climbing up a set o...  Flickr8K
1              A girl going into a wooden building .  Flickr8K
2   A little girl climbing into a wooden playhouse .  Flickr8K
3  A little girl climbing the stairs to her playh...  Flickr8K
4  A little girl in a pink dress going into a woo...  Flickr8K

Step 7 : Convert Captions to Lowercase

In [10]:
clean_df["caption"] = clean_df["caption"].str.lower()

print("Lowercase conversion completed!")

clean_df.head()

Lowercase conversion completed!

,image_path,caption,dataset
0,/content/drive/MyDrive/ImageCaptioning_MiniPro...,a child in a pink dress is climbing up a set o...,Flickr8K
1,/content/drive/MyDrive/ImageCaptioning_MiniPro...,a girl going into a wooden building .,Flickr8K
2,/content/drive/MyDrive/ImageCaptioning_MiniPro...,a little girl climbing into a wooden playhouse .,Flickr8K
3,/content/drive/MyDrive/ImageCaptioning_MiniPro...,a little girl climbing the stairs to her playh...,Flickr8K
4,/content/drive/MyDrive/ImageCaptioning_MiniPro...,a little girl in a pink dress going into a woo...,Flickr8K

##Step 8 : Remove Punctuation

In [13]:
import string

translator = str.maketrans("", "", string.punctuation)

clean_df["caption"] = clean_df["caption"].apply(
    lambda x: x.translate(translator)
)

print("Punctuation removed!")

clean_df.head()

Punctuation removed!

,image_path,caption,dataset
0,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A child in a pink dress is climbing up a set o...,Flickr8K
1,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A girl going into a wooden building,Flickr8K
2,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A little girl climbing into a wooden playhouse,Flickr8K
3,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A little girl climbing the stairs to her playh...,Flickr8K
4,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A little girl in a pink dress going into a woo...,Flickr8K

##Step 9 : Remove Extra White Spaces

In [14]:
# Remove extra spaces

clean_df["caption"] = clean_df["caption"].apply(
    lambda x: re.sub(r"\s+", " ", x).strip()
)

print("Extra spaces removed successfully!")

clean_df.head()

Extra spaces removed successfully!

,image_path,caption,dataset
0,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A child in a pink dress is climbing up a set o...,Flickr8K
1,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A girl going into a wooden building,Flickr8K
2,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A little girl climbing into a wooden playhouse,Flickr8K
3,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A little girl climbing the stairs to her playh...,Flickr8K
4,/content/drive/MyDrive/ImageCaptioning_MiniPro...,A little girl in a pink dress going into a woo...,Flickr8K

## Step 10 : Remove Empty Captions

In [15]:
before = len(clean_df)

clean_df = clean_df[
    clean_df["caption"].str.strip() != ""
]

after = len(clean_df)

print("Removed Empty Captions :", before - after)

print("Remaining Captions :", after)

Removed Empty Captions : 0
Remaining Captions : 599401

## Step 11 : Remove Very Short Captions

In [16]:
before = len(clean_df)

clean_df = clean_df[
    clean_df["caption"].apply(
        lambda x: len(x.split()) >= 3
    )
]

after = len(clean_df)

print("Removed Short Captions :", before - after)

print("Remaining Captions :", after)

Removed Short Captions : 52
Remaining Captions : 599349

Step 12 : Remove Duplicate Captions

In [17]:
before = len(clean_df)

clean_df = clean_df.drop_duplicates()

after = len(clean_df)

print("Duplicate Rows Removed :", before - after)

print("Remaining Samples :", after)

Duplicate Rows Removed : 71
Remaining Samples : 599278

## Step 13 : Add Start and End Tokens

In [18]:
clean_df["caption"] = clean_df["caption"].apply(
    lambda x: f"<start> {x} <end>"
)

print("Special tokens added successfully!")

clean_df.head()

Special tokens added successfully!

,image_path,caption,dataset
0,/content/drive/MyDrive/ImageCaptioning_MiniPro...,<start> A child in a pink dress is climbing up...,Flickr8K
1,/content/drive/MyDrive/ImageCaptioning_MiniPro...,<start> A girl going into a wooden building <end>,Flickr8K
2,/content/drive/MyDrive/ImageCaptioning_MiniPro...,<start> A little girl climbing into a wooden p...,Flickr8K
3,/content/drive/MyDrive/ImageCaptioning_MiniPro...,<start> A little girl climbing the stairs to h...,Flickr8K
4,/content/drive/MyDrive/ImageCaptioning_MiniPro...,<start> A little girl in a pink dress going in...,Flickr8K

## Step 14 : Caption Length Analysis (NEW)

In [20]:
clean_df["caption_length"] = clean_df["caption"].apply(
    lambda x: len(x.split())
)

print(clean_df["caption_length"].describe())

count    599278.000000
mean         12.956673
std           3.523712
min           5.000000
25%          11.000000
50%          12.000000
75%          14.000000
max          80.000000
Name: caption_length, dtype: float64

## Step 15 : Remove Temporary Column

In [21]:
clean_df.drop(
    columns=["caption_length"],
    inplace=True
)

## Step 16 : Save Cleaned Dataset

In [22]:
output_file = PROCESSED_DIR / "cleaned_dataset.csv"

clean_df.to_csv(
    output_file,
    index=False
)

print("Dataset saved successfully!")

print(output_file)

Dataset saved successfully!
/content/drive/MyDrive/ImageCaptioning_MiniProject/Processed/cleaned_dataset.csv

## Step 17 : Final Summary

In [23]:
print("=" * 60)
print("DATA PREPROCESSING COMPLETED")
print("=" * 60)

print()

print("Final Dataset Size :", len(clean_df))

print()

print("Dataset Distribution:")

print(clean_df["dataset"].value_counts())

print()

print(clean_df.head())

============================================================
DATA PREPROCESSING COMPLETED
============================================================

Final Dataset Size : 599278

Dataset Distribution:
dataset
COCO2017     400016
Flickr30K    158848
Flickr8K      40414
Name: count, dtype: int64

                                          image_path  \
0  /content/drive/MyDrive/ImageCaptioning_MiniPro...
1  /content/drive/MyDrive/ImageCaptioning_MiniPro...
2  /content/drive/MyDrive/ImageCaptioning_MiniPro...
3  /content/drive/MyDrive/ImageCaptioning_MiniPro...
4  /content/drive/MyDrive/ImageCaptioning_MiniPro...

                                             caption   dataset
0  <start> A child in a pink dress is climbing up...  Flickr8K
1  <start> A girl going into a wooden building <end>  Flickr8K
2  <start> A little girl climbing into a wooden p...  Flickr8K
3  <start> A little girl climbing the stairs to h...  Flickr8K
4  <start> A little girl in a pink dress going in...  Flickr8K